name: "[Discord] Announcement"

on: 
  workflow_dispatch:
    inputs:
      title:
        required: false
        default: 'Notification from Github actions'
        description: title of embed
        type: string
      content:
        required: true
        default: ''
        description: description of embed
        type: string
      url:
        required: true
        default: ''
        description: link when embed pressed
        type: string
      message:
        required: true
        default: ''
        description: discord message content
        type: string

  workflow_call:
    inputs:
      title:
        required: false
        default: 'Notification from Github actions'
        description: title of embed
        type: string
      content:
        required: true
        default: ''
        description: description of embed
        type: string
      url:
        required: true
        default: ''
        description: link when embed pressed
        type: string
      message:
        required: true
        default: ''
        description: discord message content
        type: string

jobs:
  announcement:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: "${{ secrets.DISCORD_REVANCED_UPDATE_WEBHOOK_URL }}"
        embed-title: "${{ inputs.title }}"
        embed-url: "${{ inputs.url }}"
        embed-description: "${{ inputs.content }}"
        embed-color: 3447003
        username: "Github Actions"
        avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        content: "${{ inputs.message }}"
