name: Notify YouTube Version Update

on:
  workflow_call:
    inputs:
      youtube_version:
        description: 'Latest supported YouTube version'
        required: true
        type: string

jobs:
  notify-owner:
    uses: ./.github/workflows/discord-update-owner.yml
    with:
      title: "🔄 ReVanced YouTube Supported Versions Updated"
      content: |
        ReVanced Supported YouTube version updated to **${{ inputs.youtube_version }}**
      url: "https://github.com/revanced/revanced-patches/releases/latest"
      message: "ReVanced YouTube version update completed successfully!"
    secrets: inherit

  announce:
    uses: ./.github/workflows/discord-update-announcement.yml
    with:
      title: "🔄 ReVanced YouTube Supported Versions Updated"
      content: |
        A new supported YouTube version (**${{ inputs.youtube_version }}**) is now available!
      url: "https://github.com/revanced/revanced-patches/releases/latest"
      message: "ReVanced YouTube version updated."