# Notify Patches Update Workflow
name: Notify Patches Update

on:
  workflow_call:
    inputs:
      patches_version:
        description: 'Latest patches version'
        required: true
        type: string

jobs:
  notify-owner:
    uses: ./.github/workflows/discord-update-owner.yml
    with:
      title: "🛠️ ReVanced Patches Updated"
      content: "Patches version updated to **${{ inputs.patches_version }}**."
      url: "https://github.com/revanced/revanced-patches/releases/latest"
      message: "ReVanced patches update completed successfully!"
    secrets: inherit

  # announce:
  #   uses: ./.github/workflows/discord-update-announcement.yml
  #   with:
  #     title: "🛠️ ReVanced Patches Updated"
  #     content: "A new ReVanced patches stable version (**${{ inputs.patches_version }}**) is now available!"
  #     url: "https://github.com/revanced/revanced-patches/releases/latest"
  #     message: "ReVanced patches updatd."
  #   secrets: inherit
